name: Restrict PR to Main Branch

on:
  pull_request:
    branches:
      - main

jobs:
  restrict-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check branch name
        run: |
          if [ "${{ github.head_ref }}" != "develop" ]; then
            echo "Pull requests to main can only come from the develop branch."
            exit 1
          fi
